name: Gitflow Workflow

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - develop

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  pull-requests: write
  
jobs:
  github:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
  NotifyPR:
    runs-on: ubuntu-latest
    steps:
    - name: Notify via Teams on success Approvers
      uses: simbo/msteams-message-card-action@v1.3.2
      with:
        title: "Terraform Nuevo Pull Request ${{ github.head_ref}} : ${{ github.event.number }}"
        color: 0078D7
        message: "<strong>Nuevo PR \n- <strong>GitHub Pull Request = #${{ github.event.number }} \n- <strong>Branch = ${{ github.head_ref}} \n- <strong>User = ${{ github.event.pull_request.user.login }}"
        webhook: ${{ secrets.TEAMS_WEBHOOKS_APROVADOR }}
    - run: echo ${{ github.event.pull_request.base.ref }}

  deploy_to_dev:
    uses: ./.github/workflows/repo-cross-ci-workflow.yml
    needs: NotifyPR
    secrets: inherit
    if: github.event.pull_request.base.ref == 'develop'
    with:
      teams_notifications: true
      tflint: false
      driftctl: false
      checkov: false
      kics: false
      infracost: false
      account_id: "962542038213"
      iam_role_name: "cross-role-target"
      env: "dev"
      aws_region: "us-east-1"

  # deploy_to_dev:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/dev'

  #   steps:
  #     # Add steps to deploy to production (e.g., production server)
  #     - run: terraform workspace select $BRANCH_NAME || terraform workspace new $BRANCH_NAME


  # deploy_to_prod:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/main'

  #   steps:
  #     # Add steps to deploy to production (e.g., production server)





